version: "3.7"

# used for specific settings you have outside of your docker config
# ex: proxies to external servers, storage configuration...
# remove this block entirely if not needed (Only used for Docker Swarm)
# configs:
#   caddy-basic-content:
#     file: ./Caddyfile
#     labels:
#       caddy:

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: xnok/caddy-docker-auth-portal
    # image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
      - 8443:8443
    networks:
      - docker_swarm_private
      - docker_swarm_public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # this volume is needed to keep the certificates
      # otherwise, new ones will be re-issued upon restart
      - caddy_data:/data
    deploy:
      labels: # Global options
        caddy.email: contact@nokwebspace.ovh
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: "0.1"
          memory: 200M

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    networks:
      - docker_swarm_private
    deploy:
      labels:
        caddy: whoami.dev.nokwebspace.ovh
        caddy.reverse_proxy: "{{upstreams 80}}"
        caddy.tls: "internal"

networks:
  docker_swarm_public:
    external: true
  docker_swarm_private:
    external: true

volumes:
  caddy_data: {}